#!/bin/bash

TASK_FILE="$HOME/.tasks.txt"

GREEN="\033[0;32m"
YELLOW="\033[0;33m"
RED="\033[0;31m"
MAGENTA="\033[1;35m"
RESET="\033[0m"

calculate_task_age() {
    local created=$1
    local now=$(date +%s)
    local total_seconds=$((now - created))

    local days=$((total_seconds / 86400))
    local remaining=$((total_seconds % 86400))

    local hours=$((remaining / 3600))
    local remaining=$((remaining % 3600))

    local minutes=$((remaining / 60))
    local seconds=$((remaining % 60))

    echo "${days}d ${hours}h ${minutes}m ${seconds}s"
}

command=$1

if [[ "$command" == "list" ]]; then
    echo " --- TASKS ---"

    task_num=1
    while IFS='|' read -r saved_timestamp saved_task saved_urgency; do
        age=$(calculate_task_age "$saved_timestamp")

    	if [[ "$saved_urgency" == "low" ]]; then
        	color=$GREEN
    	elif [[ "$saved_urgency" == "medium" ]]; then
        	color=$YELLOW
    	elif [[ "$saved_urgency" == "high" ]]; then
        	color=$RED
    	elif [[ "$saved_urgency" == "critical" ]]; then
        	color=$MAGENTA
        fi


	if [[ ${#saved_task} -gt 50 ]]; then
	    task_x="${saved_task:0:50}"
	    task_xs="${saved_task:50}"

	    echo "DEBUG: task_num=[$task_num]"
    	    echo "DEBUG: task_x=[$task_x]"
    	    echo "DEBUG: task_xs=[$task_xs]"
    	    echo "DEBUG: age=[$age]"

	    printf "${color}[%d] %-50s | Age: %s${RESET}\n" "$task_num" "$task_x" "$age"
            printf "${color} %s${RESET}\n" "$task_xs"
	else
	    printf "${color}[%d] %-50s | Age: %s${RESET}\n" \
                "$task_num" "$saved_task" "$age"
        fi
        ((task_num++))

    done < "$TASK_FILE"

# if command == done, let arg 2 be task id. If not specified, tell user to specify.
# use sed (Stream EDitor) to edit text in a file (-i for 'in-place' editing) (d for delete, #d means delete line #)
elif [[ "$command" == "done" ]]; then
    task_id=$2

    if [[ -z "$task_id" ]]; then
        echo "Type task done <task_number>"
        exit 1
    fi
    
    line_copy=$(sed -n "${task_id}p" "$TASK_FILE")
    task_desc=$(echo "$line_copy" | cut -d'|' -f2)
    echo "[$task_desc] completed! Great job."
    sed -i "${task_id}d" "$TASK_FILE"

# if command is not empty, then take argument 1 as task and urgency as argument 2, low if not specified.
elif [[ -n "$command" ]]; then
    task=$1
    urgency=${2:-low}

    case "${urgency,,}" in
	l|Low|low)
	    urgency="low"
	    ;;
	m|Medium|medium)
	    urgency="medium"
	    ;;
	h|High|high)
	    urgency="high"
	    ;;
	c|Critical|critical)
	    urgency="critical"
	    ;;
	*)
	    urgency="low"
	    ;;
    esac

    if [[ ! -f "$TASK_FILE" ]]; then
        touch "$TASK_FILE"
    fi

    timestamp=$(date +%s)
    echo "$timestamp|$task|$urgency" >> "$TASK_FILE" #append
    echo "Task added: $task (urgency: $urgency)"

else
    echo "Commands: "
    echo "    type task <your task> <urgency>"
    echo "    urgency is [high] [low] [medium] [critical]"
    echo "    type task list to view tasks"
fi


